[2024-05-30T15:41:41.311+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-05-30T15:41:41.340+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: s3_dag.scrap_netflix manual__2024-05-30T15:41:36.715394+00:00 [queued]>
[2024-05-30T15:41:41.349+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: s3_dag.scrap_netflix manual__2024-05-30T15:41:36.715394+00:00 [queued]>
[2024-05-30T15:41:41.352+0000] {taskinstance.py:2303} INFO - Starting attempt 1 of 2
[2024-05-30T15:41:41.361+0000] {taskinstance.py:2327} INFO - Executing <Task(PythonOperator): scrap_netflix> on 2024-05-30 15:41:36.715394+00:00
[2024-05-30T15:41:41.371+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=200) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-05-30T15:41:41.370+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 's3_dag', 'scrap_netflix', 'manual__2024-05-30T15:41:36.715394+00:00', '--job-id', '115', '--raw', '--subdir', 'DAGS_FOLDER/test.py', '--cfg-path', '/tmp/tmpdwcogf9l']
[2024-05-30T15:41:41.372+0000] {standard_task_runner.py:63} INFO - Started process 205 to run task
[2024-05-30T15:41:41.373+0000] {standard_task_runner.py:91} INFO - Job 115: Subtask scrap_netflix
[2024-05-30T15:41:41.435+0000] {task_command.py:426} INFO - Running <TaskInstance: s3_dag.scrap_netflix manual__2024-05-30T15:41:36.715394+00:00 [running]> on host cf97ea5db7f3
[2024-05-30T15:41:41.530+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='***@example.com' AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='s3_dag' AIRFLOW_CTX_TASK_ID='scrap_netflix' AIRFLOW_CTX_EXECUTION_DATE='2024-05-30T15:41:36.715394+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-05-30T15:41:36.715394+00:00'
[2024-05-30T15:41:41.532+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-05-30T15:41:41.532+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-05-30T15:41:41.533+0000] {taskinstance.py:2890} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/test.py", line 15, in download_netflix
    from src.netflix_downloader import download_netflix_data
ModuleNotFoundError: No module named 'src'
[2024-05-30T15:41:41.548+0000] {taskinstance.py:1205} INFO - Marking task as UP_FOR_RETRY. dag_id=s3_dag, task_id=scrap_netflix, execution_date=20240530T154136, start_date=20240530T154141, end_date=20240530T154141
[2024-05-30T15:41:41.563+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 115 for task scrap_netflix (No module named 'src'; 205)
[2024-05-30T15:41:41.596+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-05-30T15:41:41.614+0000] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-05-30T15:41:41.616+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
